### ISSUE TITLE
Package is not available via Package Control

### ISSUE THREAD

**Issue by jeffbyrnes** [SublimeLinter/SublimeLinter-shellcheck#1]
The README suggests that this package is available via Package Control, but that is not the case. I'd love to install it via that method, instead of manually by cloning this repository.

**Comment by tongueroo** [comment]
@jeffbyrnes Wondering if you were able to install it.  Or if there are updated install instructions. Trying to install it via Package Control and cannot seem to find sublimelinter-shellcheck. Thanks!

**Comment by tongueroo** [comment]
Nevermind. I restarted my computer and see shellcheck installed.  Unsure how but I'm good 😁

**Comment by n0ncetonic** [comment]
Looks like the actual configuration file lives in `Packages/User/Shell-Unix-Generic.sublime-settings`

**Comment by jeffbyrnes** [comment]
Yes, I was able to install if via Package Control: https://packagecontrol.io/packages/SublimeLinter-shellcheck

@n0ncetonic I’ve not had to mess about with the configuration files, so I’ve no idea why they’re differently named.
