### ISSUE TITLE
Disable linting of fish shell files

### ISSUE THREAD

**Issue by externl** [SublimeLinter/SublimeLinter-shellcheck#14]
Fish files are currently ran though shellcheck, presumably because fish has scope `source.shell.fish` and shellcheck has the settings 

```
'selector': 'source.shell - source.makefile',
```

Fish files should be excluded though either scope or filename (this would be less correct I think).

**Comment by kaste** [comment]
We're open for contribution here. Please consider making a PR. It is the fastest way to get this issue resolved. 

Usually `source.shell - source.makefile - source.shell.fish` could work, you can test this e.g. with https://github.com/kaste/HighlightScopes
