### ISSUE TITLE
Windows installation problem and solution to it

### ISSUE THREAD

**Issue by Terbiy** [SublimeLinter/SublimeLinter-shellcheck#17]
Hello! When setting SublimeLinter-shellcheck on Windows, I had freshly installed Linux subsystem from Microsoft Store. I tried to run `wsl sudo apt install shellcheck` command, but encountered the following error:

> E: Unable to locate package shellcheck

Running `wsl sudo apt update` and then `wsl sudo apt install shellcheck` helped me to solve it. Maybe this information will be useful to add to Installation part of Readme.

**Comment by kaste** [comment]
Just do it. 😁
