### ISSUE TITLE
ignore all violations in a file

### ISSUE THREAD

**Issue by ConorSheehan1** [SublimeLinter/SublimeLinter-shellcheck#23]
### Feature request

As of shellcheck 0.4.4 it's possible to disable warnings for a given file. It'd be nice to see that feature here too.

https://github.com/koalaman/shellcheck/wiki/Ignore#ignoring-all-instances-in-a-file-044

> Ignoring all instances in a file (0.4.4+)
  Add a directive at the top of the file:

      #!/bin/sh
      # shellcheck disable=SC2059

### Current behaviour
![shellcheck_file_level_ignore](https://user-images.githubusercontent.com/16896053/56748767-4f8eb600-6778-11e9-9be7-4a50d2b0bc59.png)

**Comment by braver** [comment]
This plugin simply calls the command line utility, so you should be able to use any feature supported by shellcheck. Have you got the correct version installed?

**Comment by cixtor** [comment]
I can confirm, this already works as is _(using ShellCheck v0.6.0)_.

![2019-04-25 11 25 24](https://user-images.githubusercontent.com/1933999/56759083-f4939980-674c-11e9-8d38-f73581d1af3e.gif)

**Comment by ConorSheehan1** [comment]
Sorry my bad. I thought I had shellcheck 0.5.0 (the latest [apt packaged version](https://launchpad.net/ubuntu/+source/shellcheck)), but the latest ubuntu 16.04 compatible version is 0.3.7
