### ISSUE TITLE
Add relevant GitHub topics

### ISSUE THREAD

**Issue by dominiksalvet** [SublimeLinter/SublimeLinter-shellcheck#24]
Hello! It would great if someone could add some relevant GitHub topics to this repository containing awesome software! :smiley:

**Comment by braver** [comment]
Like what? I’m puzzled. 🧐

**Comment by dominiksalvet** [comment]
E.g., the following ones: [`sublime-text`](https://github.com/topics/sublime-text), [`linter`](https://github.com/topics/linter), [`shellcheck`](https://github.com/topics/shellcheck), [`sublime-package`](https://github.com/topics/sublime-package), [`plugin`](https://github.com/topics/plugin), [`shell`](https://github.com/topics/shell), [`bash`](https://github.com/topics/bash) and [`sublime-text-plugin`](https://github.com/topics/sublime-text-plugin).

**Comment by braver** [comment]
Oh, that. We're not going to add all that to over 100 plugin repositories. They're discoverable enough via package control.

**Comment by dominiksalvet** [comment]
@braver Well, that's a shame, yet I understand you. Maybe someone will find some spare time for it in the future...
