### ISSUE TITLE
There are binary distributions of the executable

### ISSUE THREAD

**Issue by caesarsol** [SublimeLinter/SublimeLinter-shellcheck#3]
Could be stated in the README to facilitate new users:
on Debian based distros:

    apt-get install shellcheck

on OS X with homebrew:

    brew install shellcheck

**Comment by NotSqrt** [comment]
Nice !
I don't really want to keep track of all the ways to install shellcheck, so the readme already points to https://github.com/koalaman/shellcheck which explains everything ..

Is that not enough ?

**Comment by caesarsol** [comment]
your point is correct, but it states it's installable using `cabal` and it's misleading.
just a short note could incourage the users, since brew and apt are widely used!

thanks for the good work, I'm a bash addicted ;)

**Comment by NotSqrt** [comment]
I edited the messages to clarify that !
