### ISSUE TITLE
Use git sub-module's `.shellcheckrc` if present to lint sub-module

### ISSUE THREAD

**Issue by cj-wong** [SublimeLinter/SublimeLinter-shellcheck#31]
Hi,

I'm not sure if this applies generally to SublimeLinter or other supported linters. Currently, when using sub-modules via git, it's not possible for files in the sub-module to be linted using the sub-module's `.shellcheckrc`.

For example, if I have a project like this:

```
.
├── .gitmodules
└── a_submodule
    ├── .shellcheckrc
    └── some_script.sh
```

The file `some_script.sh` will show errors even if suppressed in the sub-module's `.shellcheckrc`. I could resolve this by adding ignore directives to every file, although that'd be unwieldy.

Could there be a way to address this?

**Comment by kaste** [comment]
Sorry for the late reply.  This is very likely to fix by setting the working dir.  

```
    "working_dir": "${file_path:$folder}}"
```

You can do this in the global settings or per project.  In the latter case the key would be different, if I don't misspell this here:  `"SublimeLinter.linters.shellcheck.working_dir"`.  It is just the "flat" key.

The default working dir is `$folder` btw.

**Comment by cj-wong** [comment]
Thank you very much - I was completely unaware that SublimeLinter had per-project settings. This has fixed my problem.
