### ISSUE TITLE
Support ignore options?

### ISSUE THREAD

**Issue by thuandt** [SublimeLinter/SublimeLinter-shellcheck#4]
Currently I'm using your plugins in Sublime Text3, but I can't make this ignore some linter error like SC2029.

```
            "shellcheck": {
                "@disable": false,
                "args": [],
                "exclude": "",
                "excludes": [],
                "ignore": "SC2029"
            }
```

**Comment by NotSqrt** [comment]
Doesn't it work by doing :
```
"shellcheck": {
                "@disable": false,
                "args": [],
                "exclude": "",
                "excludes": ["SC2029"],
            }
```
?

It might not, the shellcheck program might have evolved since the last time I worked on the linter.

**Comment by NotSqrt** [comment]
I edited my comment, the setting that is supposed to work for this is ``exclude``.

**Comment by thuandt** [comment]
Oh. It's work now. Thanks
