### ISSUE TITLE
Error: invalid argument

### ISSUE THREAD

**Issue by N4d4** [SublimeLinter/SublimeLinter-shellcheck#5]
does't work for me, it returns this error

> SublimeLinter: shellcheck: test.sh ['/usr/bin/shellcheck', '--format', 'gcc', '-'] 
> SublimeLinter: shellcheck output:
> shellcheck: <stdin>: hGetContents: invalid argument (invalid byte sequence)

How can I fix it??

**Comment by NotSqrt** [comment]
Well, does calling shellcheck manually on your script work ?

**Comment by N4d4** [comment]
If I open a new .sh file it works well.
But if I open an already existing .sh file, it doesn't t work even if I start it manually.
From the terminal instead shellcheck works well.

**Comment by Gui13** [comment]
I have the same issue. Using shellcheck in console works, outputs colored warnings, but from the Linter plugin in Sublime it displays the same error as above.

My computer has the french language as default, could this be the issue? 

```
LANG=fr_FR.UTF-8
LC_CTYPE=fr_FR.UTF-8
```

**Comment by Gui13** [comment]
I have another detail, executing this command:

    LC_ALL=C shellcheck myfile

In console yields the same error:

     hGetContents: invalid argument (invalid byte sequence)

**Comment by kaste** [comment]
We currently - as in the new SublimeLinter 4 - set 

```
    'LANG': 'en_US.UTF-8',
    'LC_CTYPE': 'en_US.UTF-8',
```

(A globally `LC_ALL=C` is most probably not what you want.) 

Anyway, you can modify the ENV using the linter settings. `'shellcheck': {'env': {...whatever...}}`

I'm closing bc this *should* fix the issue.
