### ISSUE TITLE
Excluding SC1036 still stops parsing

### ISSUE THREAD

**Issue by troymcginnis** [SublimeLinter/SublimeLinter-shellcheck#6]
Excluding `SC1036`, which normally stops parsing, appears to still stop the lint parser. It seems like it should continue to parse if this code is being excluded.

Thoughts?

**Comment by NotSqrt** [comment]
Hi,

Can you check the exact command being run (look at the sublime console, with sublimelinter in debug mode) ?
Can you compare the results with running the expected command manually in a shell ?

**Comment by troymcginnis** [comment]
The command being run is:

**Comment by troymcginnis** [comment]
The command being run is `SublimeLinter: shellcheck: main.sh ['/usr/local/bin/shellcheck', '--format', 'gcc', '-', '--exclude=SC1036,SC1088,SC2059,SC1091,SC2012,SC1090']`

When running the command manually in a shell, it returns no result. I suppose that makes it a shellcheck issue?

**Comment by NotSqrt** [comment]
Yes, looks like a shellcheck issue ..
