### ISSUE TITLE
"Missing" on Package Control

### ISSUE THREAD

**Issue by paxromana96** [SublimeLinter/SublimeLinter-shellcheck#8]
![screenshot 2018-02-24 13 49 54](https://user-images.githubusercontent.com/9982062/36634399-bb7787e2-1969-11e8-898d-39761fa99753.png)

I can't look up or download this package on [Package Control](https://packagecontrol.io/packages/SublimeLinter-shellcheck). It's labelled "Missing" on [packagecontrol.io](https://packagecontrol.io/packages/SublimeLinter-shellcheck), with the following error:

> Package info was unavailable last time crawler ran. Error downloading repository. HTTP exception InvalidCertificateException (Host api.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://api.github.com/repos/SublimeLinter/SublimeLinter-shellcheck.

Is this a temporary issue, or is the package down?

**Comment by kaste** [comment]
Seems Package Control is currently down. https://github.com/wbond/package_control/issues/1334
